### ISSUE TITLE
Pie chart: Warning: Failed prop type: Invalid prop `cornerRadius` of type `object` supplied to `PieArcLabel`, expected `number`.

### ISSUE THREAD

**Issue by mk48** [mui/mui-x#11054]
### Steps to reproduce

Link to live example: (required)
Go to https://mui.com/x/react-charts/pie/
Open the basic example in code sand box 
![image](https://github.com/mui/mui-x/assets/3082469/793610b1-feca-462f-9ac6-23f0e9900d72)

Open the console section
![image](https://github.com/mui/mui-x/assets/3082469/feac15e5-0a91-4cc3-a5f4-4134ab9959cd)

### Current behavior

Showing warnings

### Expected behavior

Shouldn't show any warning

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.

Browser: Firefox
```
</details>

**Search keywords**: Pie chart

**Comment by alexfauquette** [comment]
Fixed, by #10998 Should be available in the next release for stable v6. The cherry pick for v7 is still open #11045

**Comment by jsanson1747** [comment]
@alexfauquette I've just installed the newest stable version of Mui Charts (6.18.1) but this issue is still present

**Comment by alexfauquette** [comment]
Pr got merged, will be available in the next release
