### ISSUE TITLE
[data grid] Error: No row with id ... found. Caused when using getRowClassName

### ISSUE THREAD

**Issue by Abrham007** [mui/mui-x#17022]
### Steps to reproduce

Steps:
1. Open this link which leads to a demo app to reproduce this bug: ([required](https://github.com/Abrham007/data-grid-pro-bug)) 
2. Boot up the demo app and follow the steps. should be pretty straight forward

### Current behavior

Basically if you stress the `datagridpro` component for example rereander it multple times quickly and you happen to be using the `getRowClassName` then you get an odd error `Error: No row with id #673958c6-53fc-4e41-906d-f669b8eba6b6 found`.

### Expected behavior

no error 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

  System:
    OS: macOS 15.1
  Binaries:
    Node: 20.18.1 - ~/.nvm/versions/node/v20.18.1/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.18.1/bin/npm
    pnpm: 10.2.1 - ~/.nvm/versions/node/v20.18.1/bin/pnpm
  Browsers:
    Chrome: 134.0.6998.89
    Edge: Not Found
    Safari: 18.1
  npmPackages:
    @emotion/react: ^11.14.0 => 11.14.0 
    @emotion/styled: ^11.14.0 => 11.14.0 
    @mui/core-downloads-tracker:  6.4.8 
    @mui/material: 6.4.3 => 6.4.3 
    @mui/material-nextjs: 6.4.3 => 6.4.3 
    @mui/private-theming:  6.4.8 
    @mui/styled-engine:  6.4.8 
    @mui/system:  6.4.8 
    @mui/types:  7.2.24 
    @mui/utils:  6.4.8 
    @mui/x-data-grid:  7.27.0 
    @mui/x-data-grid-pro: 7.27.0 => 7.27.0 
    @mui/x-date-pickers:  7.27.0 
    @mui/x-date-pickers-pro: 7.27.0 => 7.27.0 
    @mui/x-internals:  7.26.0 
    @mui/x-license:  7.26.0 
    @types/react: 18.3.12 => 18.3.12 
    react: 18.3.1 => 18.3.1 
    react-dom: 18.3.1 => 18.3.1 
</details>

**Search keywords**: datagrid getRowClassName

**Order ID**: 108892

**Comment by arminmeh** [comment]
Is this the same issue as https://github.com/mui/mui-x/issues/16638?

**Comment by Abrham007** [comment]
it is actually similar with [this](https://github.com/mui/mui-x/pull/16631) one which is now closed b/c lack a reproducable example which I tried to provide with this issue.

**Comment by arminmeh** [comment]
@Abrham007 thanks
I will look into it

**Comment by arminmeh** [comment]
@Abrham007 I could reproduce the issue, but I also see that it is resolved in 7.28.0
Can you update and confirm that you don't see the error anymore?

**Comment by Abrham007** [comment]
Well unfortunately I kind of still see the error 

![Image](https://github.com/user-attachments/assets/05c40589-fd10-4229-8bfa-a614124c1030)

**Comment by arminmeh** [comment]
Reopened because of https://github.com/mui/mui-x/issues/16638#issuecomment-2752326767

@Abrham007 I have actually used your demo project for testing and after the changes in the PR I could reproduce the error anymore

I will check it again

**Comment by annabelhayes** [comment]
@larsmunkholm do you have the same issue when using the patched version of datagrid mentioned [here](https://github.com/mui/mui-x/issues/16638)?

i had the exact same issue before using pagination and going to a previously rendered page, but couldn't reproduce it while running this version.

**Comment by arminmeh** [comment]
@Abrham007 I have just tested the updates on the project you have linked.

Initially, I could reproduce the issue, but after adding
`"@mui/x-data-grid-pro": "https://pkg.csb.dev/mui/mui-x/commit/7cd30dad/@mui/x-data-grid-pro",`
as a dependency, the issue is gone.

For other people reporting the issue, if you are using commercial package of the grid, you have to replace the released version with the relevant patched version
so
`"@mui/x-data-grid": "https://pkg.csb.dev/mui/mui-x/commit/7cd30dad/@mui/x-data-grid",`
`"@mui/x-data-grid-pro": "https://pkg.csb.dev/mui/mui-x/commit/7cd30dad/@mui/x-data-grid-pro",`
`"@mui/x-data-grid-premium": "https://pkg.csb.dev/mui/mui-x/commit/7cd30dad/@mui/x-data-grid-premium",`

Let me know if the issue is still there for you

**Comment by Abrham007** [comment]
@arminmeh  Yea you are right I must have used the wrong patch very sorry for the inconvenience and thank you for the quick replay.

**Comment by arminmeh** [comment]
No problem.
I am glad to see that the issue is gone.

I will close this issue then.

For the other people that also mentioned that they have this issue - if you still see errors, please comment and I will reopen the issue again.

In that case, I will need a different reproduction code where the issue is still present even with the patched package.
