### ISSUE TITLE
[data grid] RangeError with custom theme

### ISSUE THREAD

**Issue by iits-steidinger** [mui/mui-x#18543]
### Steps to reproduce

When we use a custom theme including an Autocomplete with a custom React component, e.g. for the clear icon, our tests fail with a RangeError. While the problem is hard to reproduce in the browser, the Jest tests fail reliably

Here is a link to a repo reproducing the error: https://github.com/iits-steidinger/mui-x-theme-problem

### Current behavior

The DataGrid should render, but we get a RangeError:
```
> jest

 FAIL  src/App.spec.tsx
  App
    × should render (57 ms)

  ● App › should render

    RangeError: Maximum call stack size exceeded
        at JSON.stringify (<anonymous>)

      4 | describe("App", () => {
      5 |     it("should render", async () => {
    > 6 |         render(<App />)
        |               ^
      7 |     })
      8 | })

      at stringify (node_modules/@mui/x-internals/hash/stringify.js:14:15)
      at node_modules/@mui/x-data-grid/material/variables.js:15:52
      at mountMemo (node_modules/react-dom/cjs/react-dom-client.development.js:6603:23)
      at Object.useMemo (node_modules/react-dom/cjs/react-dom-client.development.js:22924:18)
      at Object.process.env.NODE_ENV.exports.useMemo (node_modules/react/cjs/react.development.js:1209:34)
      at Object.useMaterialCSSVariables [as useCSSVariables] (node_modules/@mui/x-data-grid/material/variables.js:14:16)
      at GridCSSVariablesContext (node_modules/@mui/x-data-grid/utils/css/context.js:41:36)
      at Object.react-stack-bottom-frame (node_modules/react-dom/cjs/react-dom-client.development.js:23863:20)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom-client.development.js:5529:22)
      at updateFunctionComponent (node_modules/react-dom/cjs/react-dom-client.development.js:8897:19)
      at beginWork (node_modules/react-dom/cjs/react-dom-client.development.js:10522:18)
      at runWithFiberInDEV (node_modules/react-dom/cjs/react-dom-client.development.js:1522:13)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom-client.development.js:15140:22)
      at workLoopSync (node_modules/react-dom/cjs/react-dom-client.development.js:14956:41)
      at renderRootSync (node_modules/react-dom/cjs/react-dom-client.development.js:14936:11)
      at performWorkOnRoot (node_modules/react-dom/cjs/react-dom-client.development.js:14462:44)
      at performWorkOnRootViaSchedulerTask (node_modules/react-dom/cjs/react-dom-client.development.js:16216:7)
      at flushActQueue (node_modules/react/cjs/react.development.js:566:34)
      at process.env.NODE_ENV.exports.act (node_modules/react/cjs/react.development.js:859:10)
      at node_modules/@testing-library/react/dist/act-compat.js:47:25
      at renderRoot (node_modules/@testing-library/react/dist/pure.js:190:26)
      at render (node_modules/@testing-library/react/dist/pure.js:292:10)
      at call (src/App.spec.tsx:6:15)
```

### Expected behavior

The test should succeed, as it did with v7.

### Context

The full version of our custom theme relies on some settings in the application shell, e.g. language, theme variant and a container element for popups. The demo is stripped down to the bare minimum to reproduce the problem.

### Your environment

We're currently using Jest 30, but we got the same error with Jest 29.
The tests worked fine with DataGrid v7.

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
    System:
    OS: Windows 11 10.0.26100
  Binaries:
    Node: 22.15.0 - C:\nvm4w\nodejs\node.EXE
    npm: 10.9.2 - C:\nvm4w\nodejs\npm.CMD
    pnpm: 10.12.3 - C:\nvm4w\nodejs\pnpm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Chromium (135.0.3179.98)
  npmPackages:
    @emotion/react:  11.14.0
    @emotion/styled: ^11.14.0 => 11.14.0
    @mui/core-downloads-tracker:  7.1.2
    @mui/material: ^7.1.2 => 7.1.2
    @mui/private-theming:  7.1.1
    @mui/styled-engine:  7.1.1
    @mui/system:  7.1.1
    @mui/types:  7.4.3
    @mui/utils:  7.1.1
    @mui/x-data-grid: ^8.5.3 => 8.5.3
    @mui/x-internals:  8.5.3
    @types/react: ^19.1.8 => 19.1.8
    react: ^19.1.0 => 19.1.0
    react-dom: ^19.1.0 => 19.1.0
    typescript: ~5.8.3 => 5.8.3

```
</details>

**Search keywords**: RangeError

**Comment by kenanyusuf** [comment]
Hi @iits-steidinger thanks for providing the repo. I checked it out and ran the tests but everything is passing for me:

<img width="342" alt="Image" src="https://github.com/user-attachments/assets/40c4fef7-ba19-474f-b73f-b9a60ed46709" />

@michelengelen could you try as well?

**Comment by michelengelen** [comment]
Works like a charm on node v20 and node v22

<img width="727" alt="Image" src="https://github.com/user-attachments/assets/4c32ccb3-8ac8-483c-8804-69048fe5a574" />

Could it be windows related (i doubt it though)? @noraleonte could you give this a try please?

**Comment by iits-steidinger** [comment]
Thanks for the quick feedback. I added a matrix build to the repo and the test works on Ubuntu, but fails on Windows: 

![Image](https://github.com/user-attachments/assets/7c70b525-d0f9-49e9-a004-0edc75995846)

https://github.com/iits-steidinger/mui-x-theme-problem/actions/runs/15921571314/job/44909343555

I hope that helps.

**Comment by michelengelen** [comment]
> Thanks for the quick feedback. I added a matrix build to the repo and the test works on Ubuntu, but fails on Windows:
> 
> https://github.com/iits-steidinger/mui-x-theme-problem/actions/runs/15921571314/job/44909343555
> 
> I hope that helps.

Yes, that helps ... seems like this is related to windows ... to be sure we'll wait for the input from @noraleonte

**Comment by michelengelen** [comment]
According to the callstack this seems to be a problem with the `stringify` function. Since this is a very small function with a limited scope isolating and fixing this shouldn't be a problem... I'll add it to the board! 👍🏼

**Comment by noraleonte** [comment]
I just ran the tests both on WSL and Windows. WSL passes, Windows fails 😬 

![Image](https://github.com/user-attachments/assets/525b42a0-e6ed-4022-85f9-d2a8e880c158)

![Image](https://github.com/user-attachments/assets/fc13582e-76a8-4b57-ab40-77ea776b3aab)

**Comment by kachkaev** [comment]
I faced a possibly related issue after migrating `@mui/x-data-grid-pro` from v7 to v8. We used to have a custom theme injected via `ThemeProvider`. The theme itself was static (defined as `const` outside React tree).

When `DataGridPro` was mounted, its rendering took a while. If several tables were mounted, performance was getting worse linearly.

I used React Profiler to investigate this issue and found a bottleneck here:

https://github.com/mui/mui-x/blob/4350bf38d02886f79a1e2e2c4dfe2ae4890a9ea4/packages/x-data-grid/src/utils/css/context.tsx#L26-L45

### One grid instance

![Image](https://github.com/user-attachments/assets/6d5c36ba-8a41-4b0a-81a1-a3d987428a99)

### Five grid instances

![Image](https://github.com/user-attachments/assets/2e2fd1c3-82eb-4c6e-9261-dafa2007ac95)

It looks like the injection of the `<style>` tag is what was causing the problem. Once I removed `ThemeProvider`, performance went back to normal.

**Comment by kenanyusuf** [comment]
@romgrk could you take a look at this one?

**Comment by romgrk** [comment]
@kachkaev The performance issue is a different problem, please file a separate issue so we can keep those discussions isolated. Could you also include a reproduction case? That runtime cost for `GridCSSVariablesContext` is higher than what I see with the standard setup.

@KenanYusuf Do you mean the perf issue or the original one as well? I'm on linux, but I could try booting a windows VM to debug the issue.

**Comment by romgrk** [comment]
For the stringify-on-windows issue, #18512 that we merged today and should release today/tomorrow with the v8.7.0 release might fix things.

**Comment by iits-steidinger** [comment]
Unfortunately, it doesn't fix this issue. I tested it in our app and in the reproducer, both still fail:

<img width="1958" height="1415" alt="Image" src="https://github.com/user-attachments/assets/946cde4e-a4f2-4242-94b0-f40da584ef58" />
https://github.com/iits-steidinger/mui-x-theme-problem/actions/runs/16109377425/job/45450021795

**Comment by KryptoBeard** [comment]
I get this error a ton now when developing our app on windows. Doesn't seem to occur when deployed to a Linux app service that I can tell.

**Comment by michelengelen** [comment]
Thanks for the reproduction repo and the CI matrix, @iits-steidinger. This should be fixed by #19427. The grid no longer runs the generic `stringify()` over the theme. A dedicated serializer now skips React elements (your custom clear icon) and circular structures, so the deep recursion from your stack trace cannot happen anymore.

The fix shipped in [v8.11.2](https://github.com/mui/mui-x/releases/tag/v8.11.2) and is included in v9. Note that #18512 (v8.7.0), which we suggested earlier, only covered `window`/`document` references, which is why your re-test still failed.

Can you run your Windows CI matrix against v8.11.2 or later? I will close this issue as resolved. Comment here if the `RangeError` still appears on the latest version.
