### ISSUE TITLE
[charts] Series highlight demo not working properly

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-x#19433]
### Steps to reproduce

Steps:

1. Open this link to live example: https://mui.com/x/react-charts/highlighting/#highlighting-series
2. Currently, only the scatter chart responds to the drop-down options, while the other three charts don't react.

On the same page, https://mui.com/x/react-charts/highlighting/#synchronizing-highlights also seem to not work.

### Expected behavior

These demos work in v7: https://v7.mui.com/x/react-charts/highlighting/

**Search keywords**: highlight series

**Comment by nyates42** [comment]
I am also experiencing the same issue. Demo also broken here:
https://mui.com/x/react-charts/pie/#highlight

**Comment by michelengelen** [comment]
Adding it to the board ... @JCQuintas could you have a look?

**Comment by zoie0312** [comment]
Controlled item and Synchronizing highlights still not working  

[https://mui.com/x/react-charts/highlighting/#controlled-item-highlight](url)  
[https://mui.com/x/react-charts/highlighting/#synchronizing-highlights](url)

**Comment by bernardobelchior** [comment]
Thanks for the report, @zoie0312! Fixed by https://github.com/mui/mui-x/pull/20627

**Comment by zoie0312** [comment]
@bernardobelchior is the example on doc using latest code ? If yes, then I think they're not fixed.  
Take Synchronizing Highlights for example, the expected behavior should be like v7, https://v7.mui.com/x/react-charts/highlighting/, hovering over a bar should also highlight the corresponding slice in pie chart and vice versa. But it's not on v8. I think the Controlled Item Highlight has similar issue.

**Comment by bernardobelchior** [comment]
@zoie0312 the fix was merged after last week's release, so it wasn't deployed to the docs. It'll be deployed with this week's release
