### ISSUE TITLE
[charts-pro] Image/PDF export blocked by CSP nonce (App Router + AppRouterCacheProvider)

### ISSUE THREAD

**Issue by jackyyang-maker** [mui/mui-x#20037]
### Summary

Description
Hi MUI X team 👋

We’re on Next.js App Router and use AppRouterCacheProvider with a strict CSP. Other MUI components respect the nonce, but @mui/x-charts-pro export gets blocked by CSP.

**CSP (simplified):**
```
style-src-elem 'self' 'nonce-${nonce};
style-src-attr 'unsafe-inline';
```

**Provider:**
```
// layout.tsx
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
<AppRouterCacheProvider options={{ enableCssLayer: true, nonce }}>
</AppRouterCacheProvider>
```

**Environment**

- @mui/x-charts-pro: 8.14.0
- @mui/x-charts: 8.14.0
- @mui/material: 7.1.1
- @mui/material-nextjs: 7.1.1
- @emotion/cache: 11.14.0
- "react": "19.1.1"
- "next": "15.4.7"

Next.js App Router (Chrome/Edge latest)

**Console excerpt**
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src-elem 'self' 'nonce-…'"

### Examples

For example, similar to how the DataGrid component provides a nonce prop ([docs here](https://mui.com/x/api/data-grid/data-grid/#data-grid-prop-nonce)
), it would be helpful if @mui/x-charts-pro could also accept a nonce—either as a prop or automatically injected through AppRouterCacheProvider—so that any <style> tags generated during the export process include the proper nonce for CSP compliance.

**Observed:** Clicking export (image/PDF) triggers a CSP violation for a <style> (or inline style) created during export. Other MUI components (Dialogs/Popovers/etc.) work under the same CSP.

**Expected**
Export should inherit or allow passing a nonce so any dynamically created <style> elements (and, if applicable, inline styles) comply with CSP.

**Minimal repro idea**
A Next.js App Router page rendering <BarChartPro /> <LineChartPro/> with the toolbar export enabled + CSP headers above. I can provide a sandbox or repo if needed.
Thanks for looking into nonce support for charts export 🙏

**Search keywords**: chart, export, nonce

**Comment by bernardobelchior** [comment]
Hey, @jackyyang-maker! Thanks for opening this issue. I'll take a look to see what can be done here. 

If you could provide a reproduction it would help us immensely so we can actually verify that a fix works.

**Comment by jackyyang-maker** [comment]
Hey, [bernardobelchior](https://github.com/bernardobelchior),
Here is the example in codesandbox.
https://codesandbox.io/p/devbox/lively-framework-3z6rql

I added a simple CSP rule in my middleware.ts, following the [official Next.js example](https://nextjs.org/docs/15/app/guides/content-security-policy)
And using the official example component: https://mui.com/x/react-charts/export/#default-toolbar
when clicking the export as PNG button, the following error occurs:

`Error: Cannot read properties of null (reading 'cssRules')`

The export feature fails to work under this CSP setup.

<img width="823" height="638" alt="Image" src="https://github.com/user-attachments/assets/5cd4e324-be6f-4445-9225-0730cd85877b" />

**Comment by bernardobelchior** [comment]
Hey, @jackyyang-maker. 

I think I managed to fix the print export by providing a nonce ([PR](https://github.com/mui/mui-x/pull/20053)). 

You can try the fix by installing the charts packages like this: `npm i https://pkg.pr.new/mui/mui-x/@mui/x-charts-pro@cd61395 https://pkg.pr.new/mui/mui-x/@mui/x-charts@cd61395`

You can provide the nonce through `slotProps`:

```
 slotProps={{ toolbar: { printOptions: { nonce } } }}
```

Can you check if this works? I had to clean the `.next` directory to ensure a clean build.

The image export is trickier, but if this works for the print export, I can try to fix it for the image export as well.

**Comment by jackyyang-maker** [comment]
Hey, [bernardobelchior](https://github.com/bernardobelchior),
Tested it — the print export works fine now.
Please go ahead and continue with the image export fix. Thanks.

**Comment by bernardobelchior** [comment]
@jackyyang-maker I managed to find a solution for the image export, but it requires adding the following line to the `Content-Security-Policy`: `img-src 'self' data: blob:`. This is required due to how the library we're using for transforming the SVG into an image works. Is that an acceptable compromise for you?

**Comment by jackyyang-maker** [comment]
[bernardobelchior](https://github.com/bernardobelchior), Thanks for the update! Yes, adding `img-src 'self' data: blob:` to the CSP is acceptable for me.  
I'll update the middleware and test it on my side.  
I'll let you know if I run into anything. Thanks again!

**Comment by bernardobelchior** [comment]
@jackyyang-maker just a heads-up: I'm still working on this, but it requires changes to 3rd party dependencies. I'm waiting on a PR to be approved and merged before I can fix this on our side.

**Comment by jackyyang-maker** [comment]
[bernardobelchior](https://github.com/bernardobelchior) Just checking in — do you still need anything from our side?
The last update mentioned waiting for a 3rd-party PR, so please let me know if any additional info is required.

**Comment by bernardobelchior** [comment]
@jackyyang-maker the PRs to 3rd party dependencies were merged over the weekend. I'll work on having our PR ready to review this week. I think we'll likely have this issue resolved by next week's release, or maybe this week if we're lucky.

**Comment by jackyyang-maker** [comment]
[bernardobelchior](https://github.com/bernardobelchior) Thanks for the update!
Let me know if there’s anything you need from my side.
Looking forward to the review.

**Comment by bernardobelchior** [comment]
@jackyyang-maker the PR was just merged. You should see the changes in this week's release. Let me know if something isn't working as expected.

**Comment by bernardobelchior** [comment]
This week's release (v8.18.0) already includes the mentioned PR. @jackyyang-maker, can you let me know if the issue is fixed with these changes?

**Comment by jackyyang-maker** [comment]
[bernardobelchior](https://github.com/bernardobelchior) Thanks for the update. I tested again, and even though the nonce is correctly passed through our layout context and received by the chart component, the export pipeline still injects several inline <style> tags that never receive that nonce.

These styles are generated internally by rasterizeHTML during the export process, and since they don’t go through React or our provider layer, they cannot inherit or be patched with the nonce.

So effectively:

- Passing a nonce works only for the parts we control.
- The export flow still inserts additional <style> elements without a nonce.
- Because of that, style-src cannot rely on a nonce for this feature.

From a CSP standpoint, the only option that allows chart export to work reliably is enabling 'unsafe-inline' for style-src.

Here’s a screenshot showing the issue more clearly.
The nonce is correctly passed through our layout context, but the export process still injects additional <style> tags that do not receive this nonce, so CSP blocks them. These styles are generated internally by inline.js and rasterizeHTML.js, and cannot inherit or be patched with our nonce.
Because of that, the export feature cannot rely on a nonce-based style-src.

<img width="1881" height="137" alt="Image" src="https://github.com/user-attachments/assets/8d5fa145-381c-41ac-a843-07f29db746cb" />

**Comment by bernardobelchior** [comment]
@jackyyang-maker what version of rasterizeHTML are you on? I forgot to let you know that you need to upgrade it to [v1.4.0](https://github.com/cburgmer/rasterizeHTML.js/releases/tag/1.4.0), which is where I added nonce support

**Comment by jackyyang-maker** [comment]
[bernardobelchior](https://github.com/bernardobelchior) 
I upgraded rasterizeHTML to v1.4.0, and confirmed that the chart component is correctly receiving the nonce through our layout context.

However, the export pipeline is still triggering CSP violations.
Inline <style> elements created during export still do not receive the nonce, so the browser blocks them.

Here is what I’m currently running:
### Packages
- @mui/x-charts: 8.18.0
- @mui/x-charts-pro: 8.18.0
- rasterizehtml: 1.4.0

### CSP (dev)
`default-src 'self';
script-src 'self' 'nonce-${nonce}' 'unsafe-eval';
style-src-elem 'self' 'nonce-${nonce}';
style-src-attr 'unsafe-inline';  // required by MUI
connect-src 'self' …;
img-src 'self' blob: data: …;
font-src 'self';
object-src 'none';
base-uri 'self';
form-action 'self';
frame-ancestors 'none';
`

### CSP (prod)
`default-src 'self';
script-src 'self' 'nonce-${nonce}' 'strict-dynamic';
style-src-elem 'self' 'nonce-${nonce}';
style-src-attr 'unsafe-inline';  // required by MUI
connect-src 'self' …;
img-src 'self' blob: data: …;
font-src 'self';
object-src 'none';
base-uri 'self';
form-action 'self';
frame-ancestors 'none';
upgrade-insecure-requests;
`
### Current issue
Even after upgrading to 1.4.0, the export process still injects multiple inline <style> tags without the nonce.
Because a nonce is present, the browser treats 'unsafe-inline' as disabled, so these injected styles are blocked:
`Applying inline style violates the following CSP directive
'style-src-elem 'self' 'nonce-xxxx''
`
These styles appear to be generated internally by rasterizeHTML, so they never pass through React or our layout layer where the nonce is applied.
Let me know if there’s anything else I can test — happy to try additional builds.

**Comment by bernardobelchior** [comment]
@jackyyang-maker thanks for you comment. I've been again trying to understand what the issue is. 

Would you be able to test [this PR](https://github.com/mui/mui-x/pull/20395) out and see if it fixes the issue for you? It did in my tests, at least. It should be enough to do `npm i https://pkg.pr.new/mui/mui-x/@mui/x-charts-pro@9b256e8`.

**Comment by jackyyang-maker** [comment]
Hi [bernardobelchior](https://github.com/bernardobelchior),

I appreciate the snapshot build provided. I tested with @mui/x-charts-pro@9b256e8, but unfortunately, the issue persists.

1. Environment Verification (It works normally) Just to confirm my setup is correct: The chart renders perfectly fine in the browser initially (see the first screenshot below). This proves that the nonce is correctly configured in the AppRouterCacheProvider for standard rendering.

2. The Failure (Export Only) The CSP violation only triggers when I click the export button.

3. Detailed Error Logs The console reveals multiple blocking points where the nonce is missing:

inline.js:143

rasterizeHTML.js:681

Followed by a crash: TypeError: Cannot read properties of null (reading 'cssRules') (caused by the blocked styles).

It seems the nonce is not being passed down to the internal rasterizeHTML / style-inlining utilities used during the export process.

### Packages
@mui/x-charts: 8.18.0
@mui/x-charts-pro: https://pkg.pr.new/mui/mui-x/@mui/x-charts-pro@9b256e8
rasterizehtml: 1.4.0

### Screenshots:
<img width="1885" height="298" alt="Image" src="https://github.com/user-attachments/assets/26fae899-797a-41ea-a058-de42ec4eadec" />
<img width="1143" height="409" alt="Image" src="https://github.com/user-attachments/assets/39aa4dbe-35c4-4f13-85c5-0d33893d469d" />

**Comment by bernardobelchior** [comment]
@jackyyang-maker thanks for the information.

Would you be able to test while also updating the `@mui/x-charts` library to that specific commit (`https://pkg.pr.new/mui/mui-x/@mui/x-charts@9b256e8`)?

If you could share the output of `npm ls @mui/x-charts` and `npm ls @mui/x-charts-pro` so we can be sure that the libraries are using the correct version I'd appreciate it.

**Comment by jackyyang-maker** [comment]
Hi [bernardobelchior](https://github.com/bernardobelchior), I tried installing the commit version you provided, but it seems that the package cannot be installed correctly.

@mui/x-charts-pro is still locked at version 8.18.0, and there is no matching PR commit for x-charts-pro. As a result, npm always resolves back to @mui/x-charts@8.18.0, marks it as invalid, and throws ELSPROBLEMS.

Could you provide a matching preview build of both @mui/x-charts and @mui/x-charts-pro for commit 9b256e8 so that the peer dependencies align?

Here is the output of npm ls after installation:
### Packages
@mui/x-charts: https://pkg.pr.new/mui/mui-x/@mui/x-charts@9b256e8)
@mui/x-charts-pro: https://pkg.pr.new/mui/mui-x/@mui/x-charts-pro@9b256e8
rasterizehtml: 1.4.0

<img width="1537" height="209" alt="Image" src="https://github.com/user-attachments/assets/a0e3940c-ea0e-42ed-a16e-f323db51a251" />
<img width="527" height="80" alt="Image" src="https://github.com/user-attachments/assets/bf5246ec-6bd1-4cb8-b952-c19fda5b0cd9" />

**Comment by bernardobelchior** [comment]
If `@mui/x-charts-pro` is in your dependencies, you don't need to install `@mui/x-charts` since the former depends on the latter. That should help fixing the issue. 

Nevertheless, can you try installing both dependencies by doing `npm i https://pkg.pr.new/mui/mui-x/@mui/x-charts@9b256e8 https://pkg.pr.new/mui/mui-x/@mui/x-charts-pro@9b256e8`?

**Comment by jackyyang-maker** [comment]
Hi, [bernardobelchior](https://github.com/bernardobelchior) thanks for the preview build.

I have successfully installed the commit version (using overrides). I verified the installation by checking node_modules/@mui/x-charts/package.json, and the internal dependencies (like @mui/x-charts-vendor) are correctly pointing to the https://pkg.pr.new/... URLs with commit 9b256e8.

However, even after deleting the .next cache folder and restarting the server, the issue still persists. The behavior remains the same as before.

Is there anything else I need to check? Or does this PR cover my specific case?

### package informations
**node_modules/@mui/x-charts/package.json**

> {
>   "name": "@mui/x-charts",
>   "version": "8.18.0",
>   "author": "MUI Team",
>   "description": "The community edition of MUI X Charts components.",
>   "license": "MIT",
>   "bugs": {
>     "url": "https://github.com/mui/mui-x/issues"
>   },
>   "homepage": "https://mui.com/x/react-charts/",
>   "sideEffects": false,
>   "publishConfig": {
>     "access": "public"
>   },
>   "keywords": [
>     "react",
>     "react-component",
>     "mui",
>     "mui-x",
>     "material-ui",
>     "material design",
>     "charts"
>   ],
>   "repository": {
>     "type": "git",
>     "url": "git+https://github.com/mui/mui-x.git",
>     "directory": "packages/x-charts"
>   },
>   "dependencies": {
>     "@babel/runtime": "^7.28.4",
>     "@mui/utils": "^7.3.5",
>     "@mui/x-charts-vendor": "https://pkg.pr.new/mui/mui-x/@mui/x-charts-vendor@9b256e8f8d222650fc4d4639e4fe0b0d5f52a441",
>     "@mui/x-internal-gestures": "https://pkg.pr.new/mui/mui-x/@mui/x-internal-gestures@9b256e8f8d222650fc4d4639e4fe0b0d5f52a441",
>     "@mui/x-internals": "https://pkg.pr.new/mui/mui-x/@mui/x-internals@9b256e8f8d222650fc4d4639e4fe0b0d5f52a441",
>     "bezier-easing": "^2.1.0",
>     "clsx": "^2.1.1",
>     "flatqueue": "^3.0.0",
>     "prop-types": "^15.8.1",
>     "reselect": "^5.1.1",
>     "use-sync-external-store": "^1.6.0"
>   },
>   "peerDependencies": {
>     "@emotion/react": "^11.9.0",
>     "@emotion/styled": "^11.8.1",
>     "@mui/material": "^5.15.14 || ^6.0.0 || ^7.0.0",
>     "@mui/system": "^5.15.14 || ^6.0.0 || ^7.0.0",
>     "react": "^17.0.0 || ^18.0.0 || ^19.0.0",
>     "react-dom": "^17.0.0 || ^18.0.0 || ^19.0.0"
>   },
>   "peerDependenciesMeta": {
>     "@emotion/react": {
>       "optional": true
>     },
>     "@emotion/styled": {
>       "optional": true
>     }
>   },
>   "engines": {
>     "node": ">=14.0.0"
>   },
>   "type": "commonjs",
>   "main": "./index.js",
>   "types": "./index.d.ts",
>   "exports": {
>     "./package.json": "./package.json",
>     ".": {
>       "require": {
>         "types": "./index.d.ts",
>         "default": "./index.js"
>       },
>       "default": {
>         "types": "./esm/index.d.ts",
>         "default": "./esm/index.js"
>       }
>     },
>     "./*": {
>       "require": {
>         "types": "./*/index.d.ts",
>         "default": "./*/index.js"
>       },
>       "default": {
>         "types": "./esm/*/index.d.ts",
>         "default": "./esm/*/index.js"
>       }
>     },
>     "./esm": null
>   }
> }


**My project packages**

>   "dependencies": {
>     "@emotion/cache": "11.14.0",
>     "@emotion/react": "11.14.0",
>     "@emotion/styled": "11.14.0",
>     "@hello-pangea/dnd": "^18.0.1",
>     "@hookform/resolvers": "^5.1.1",
>     "@mui/icons-material": "7.1.1",
>     "@mui/material": "7.1.1",
>     "@mui/material-nextjs": "7.1.1",
>     "@mui/x-charts": "https://pkg.pr.new/mui/mui-x/@mui/x-charts@9b256e8",
>     "@mui/x-charts-pro": "https://pkg.pr.new/mui/mui-x/@mui/x-charts-pro@9b256e8",
>     "@mui/x-data-grid": "8.5.2",
>     "@mui/x-date-pickers": "8.5.1",
>     "@mui/x-license": "^8.14.0",
>     "@mui/x-tree-view": "8.5.1",
>     "@react-spring/web": "^10.0.1",
>     "@redux-devtools/extension": "^3.3.0",
>     "@reduxjs/toolkit": "^2.8.2",
>     "@tanstack/react-query": "5.85.5",
>     "@tanstack/react-virtual": "3.13.12",
>     "accept-language": "^3.0.20",
>     "dayjs": "^1.11.13",
>     "dompurify": "^3.2.6",
>     "i18next": "^25.2.1",
>     "i18next-browser-languagedetector": "^8.2.0",
>     "i18next-http-backend": "^3.0.2",
>     "i18next-resources-to-backend": "^1.2.1",
>     "next": "15.4.7",
>     "next-auth": "^4.24.11",
>     "pdfjs-dist": "4.8.69",
>     "query-string": "^9.2.2",
>     "rasterizehtml": "1.4.0",
>     "react": "19.1.1",
>     "react-cookie": "^8.0.1",
>     "react-dom": "19.1.1",
>     "react-error-boundary": "^6.0.0",
>     "react-hook-form": "^7.58.1",
>     "react-i18next": "^15.5.3",
>     "react-pdf": "9.2.1",
>     "react-redux": "^9.2.0",
>     "zod": "^3.25.67",
>     "zustand": "^5.0.8"
>   },
>   "overrides": {
>     "@mui/x-charts": "https://pkg.pr.new/mui/mui-x/@mui/x-charts@9b256e8",
>     "@mui/x-charts-pro": "https://pkg.pr.new/mui/mui-x/@mui/x-charts-pro@9b256e8"
>   },
>   "devDependencies": {
>     "@eslint/eslintrc": "^3",
>     "@tanstack/react-query-devtools": "5.85.5",
>     "@types/node": "20.19.2",
>     "@types/react": "19",
>     "@types/react-dom": "19",
>     "eslint": "9",
>     "eslint-config-next": "15.4.7",
>     "typescript": "5.8.3"
>   }
>

**Comment by bernardobelchior** [comment]
@jackyyang-maker, a new attempt at a fix was just released in 8.20.0. If that doesn't work, would you be able to create a reproduction and share it so I can try to fix it? From my tests, 8.20.0 should be working.

**Comment by jackyyang-maker** [comment]
Hi,[bernardobelchior](https://github.com/bernardobelchior) thanks for the update.

I have upgraded to v8.20.0, but unfortunately, the chart export nonce issue persists and has not been resolved in my environment.

Here are the details:

Version Verification: I confirmed that I am running @mui/x-charts(-pro)@8.20.0. 

<img width="558" height="115" alt="Image" src="https://github.com/user-attachments/assets/968f84c3-330a-4ac7-9371-51668ade5c5c" />

<img width="571" height="75" alt="Image" src="https://github.com/user-attachments/assets/5346d9f6-4452-49ff-b3a8-ca21ab73ba77" />

<img width="568" height="113" alt="Image" src="https://github.com/user-attachments/assets/5bfb9364-3503-471a-91a4-62dd1cb46e07" />

The Error: When triggering the export, I still hit the CSP violation regarding inline styles, which seemingly leads to a crash in rasterizeHTML.js.

CSP Error: Applying inline style violates the following Content Security Policy directive...

Stack Trace: TypeError: Cannot read properties of null (reading 'cssRules') at rasterizeHTML.js.

It seems that the export logic is still attempting to inject styles in a way that conflicts with the strict CSP nonce setup, preventing access to cssRules.

<img width="1857" height="120" alt="Image" src="https://github.com/user-attachments/assets/f05efe7a-4eec-40eb-906b-8c957a2b4c6d" />
<img width="1891" height="233" alt="Image" src="https://github.com/user-attachments/assets/ca36a2d9-a113-4b0a-bfe3-0f214c94d95a" />

Could you please take another look? Thanks!

**Comment by bernardobelchior** [comment]
I've now been able to reproduce your issue. I'll continue looking.

**Comment by bernardobelchior** [comment]
@jackyyang-maker I investigated and there seems to be an issue with out last release. Not all code changes were released, so some of the changes I made aren't available in v8.20. 

This week's release should include all changes, which should fix the issue for good. Let's wait for that and try again.

**Comment by jackyyang-maker** [comment]
[bernardobelchior](https://github.com/bernardobelchior) Thanks for checking 👍  
Got it — let's wait for this week's release and verify again once it's deployed.

**Comment by bernardobelchior** [comment]
@jackyyang-maker the release is out already. It's v8.21.0. Let me know if it works for you 😄

**Comment by jackyyang-maker** [comment]
Thanks for the update. I've tested with the latest changes, but unfortunately, the issue persists in my environment.

To help identify the root cause, I'd like to share our specific setup. We are using Next.js App Router with react-i18next, which requires specific middleware logic to handle locale redirects while injecting the CSP nonce.

Here is the exact configuration we are running:

**1. CSP Configuration**
We strictly enforce style-src-elem with a nonce.
Development:
`
default-src 'self';
script-src 'self' 'nonce-${nonce}' 'unsafe-eval';
style-src-elem 'self' 'nonce-${nonce}';
style-src-attr 'unsafe-inline';
connect-src 'self' ${connectSrcWhiteList};
img-src 'self' blob: data: ${imgSrcWhiteList};
font-src 'self';
object-src 'none';
base-uri 'self';
form-action 'self';
frame-ancestors 'none';
`
Production:
`default-src 'self';
script-src 'self' 'nonce-${nonce}' 'strict-dynamic';
style-src-elem 'self' 'nonce-${nonce}';
style-src-attr 'unsafe-inline';
connect-src 'self' ${connectSrcWhiteList};
img-src 'self' blob: data: ${imgSrcWhiteList};
font-src 'self';
object-src 'none';
base-uri 'self';
form-action 'self';
frame-ancestors 'none';
upgrade-insecure-requests;
`

**2. Middleware Setup (middleware.ts)**
Our middleware handles both i18n redirects and CSP header injection. We pass the nonce via x-nonce to the request headers for the server components to consume.

```
import { NextRequest, NextResponse } from "next/server";
import acceptLanguage from "accept-language";
import { fallbackLng, languages, cookieName } from "@/i18n/config";
import { Locale } from "@/types/locale";
import { getCSPHeaderAndNonce, setCspHeader } from "@/lib/security/csp";

acceptLanguage.languages(languages);

export function handleI18nMiddleware(req: NextRequest) {
  const lng = req.cookies.get(cookieName)?.value
    ? acceptLanguage.get(req.cookies.get(cookieName)!.value)
    : acceptLanguage.get(req.headers.get("Accept-Language")) || fallbackLng;

  const isDocNav =
    req.headers.get("sec-fetch-dest") === "document" &&
    req.headers.get("sec-fetch-mode") === "navigate";

  const pathname = req.nextUrl.pathname;
  const first = pathname.split("/")[1];
  const hasPrefix = languages.includes(first as Locale);

  if (!hasPrefix && !pathname.startsWith("/_next")) {
    const url = req.nextUrl.clone();
    url.pathname = `/${lng}${pathname}`;
    const res = NextResponse.redirect(url);
    const { csp, nonce } = getCSPHeaderAndNonce();
    
    setCspHeader(res, csp, nonce);
    res.cookies.set(cookieName, lng || "");
    return { lng, response: res };
  }

  if (isDocNav) {
    const { csp, nonce } = getCSPHeaderAndNonce();
    const reqHeaders = new Headers(req.headers);
    reqHeaders.set("x-nonce", nonce);
    
    const res = NextResponse.next({ request: { headers: reqHeaders } });
    setCspHeader(res, csp, nonce);
    return { lng, response: res };
  }

  return { lng, response: NextResponse.next() };
}
```

It seems that even with AppRouterCacheProvider configured, the export functionality might still be generating styles (likely <style> elements) that do not inherit this nonce provided by the middleware context, causing them to be blocked by style-src-elem.

<img width="583" height="80" alt="Image" src="https://github.com/user-attachments/assets/5025e4c9-b70d-4f12-b7c0-1f02887156cb" />
<img width="1884" height="329" alt="Image" src="https://github.com/user-attachments/assets/6f0b22b4-11c9-4910-8b9f-fd5878780214" />

**Comment by bernardobelchior** [comment]
@jackyyang-maker that's unfortunate. Would you be able to create a minimal reproduction in StackBlitz or CodeSandbox? I don't know how else I can reproduce this issue as I've already tried using the CSP header from your comment in a NextJS repo and I don't see any errors.

**Comment by jackyyang-maker** [comment]
Hi @bernardobelchior, here is the CodeSandbox example:
https://codesandbox.io/p/devbox/lively-framework-3z6rql

Apologies for the delayed response — we’ve been quite busy with our project recently.

We’ve narrowed the issue down further and found that the problem is related to the Roboto font integration.

In our AppTheme(@/themes/AppTheme.tsx), we are using `next/font/google` to load Roboto and applying it via MUI typography:

```ts
const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

typography: {
  fontFamily: roboto.style.fontFamily,
},
```
When this Roboto setup is present, the chart export fails with the same cssRules === null error.
If we comment out the Roboto-related code (keeping ThemeProvider, cssVariables, CSP, and nonce unchanged), the export works correctly.

Additionally, we found that simply initializing Roboto via next/font/google is enough to trigger the issue, even if the font is not applied to the theme or used in any component.
In other words, just having:

```ts
const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});
```
in the codebase already causes the export to fail.

This suggests the issue is triggered by how styles injected by next/font are added to the document, rather than how the font is consumed by MUI. It also explains why removing the Roboto initialization alone resolves the problem.

Overall, this seems related to how styles injected by next/font (combined with MUI ThemeProvider / cssVariables) are represented in document.styleSheets and accessed during the rasterizeHTML export process.

**Comment by bernardobelchior** [comment]
@jackyyang-maker thanks for the reproduction. I'm still investigating, but from my tests a fix to a downstream dependency solves the issue in the reproduction you provided. We'll have to wait for it to be approved and merged. I'll let you know once the fix has been released.

**Comment by oliverjohns** [comment]
I can add that we're experiencing this issue aswell, since we are using this import statement:
`import { Public_Sans } from 'next/font/google';` 

@bernardobelchior Thanks for your support on this, can you link that PR here so we can follow along?

**Comment by alexfauquette** [comment]
I think it's this PR: https://github.com/cburgmer/inlineresources/pull/43

**Comment by oliverjohns** [comment]
@bernardobelchior Hi, https://github.com/cburgmer/inlineresources/pull/43 has been merged now ✌️

**Comment by bernardobelchior** [comment]
Hey, @oliverjohns. Thanks for the heads up. 

`rasterizehtml`'s `package.json` specifies `inlineresources` as `^1.1.0`, so you should be able to run `npm install inlineresources@1.2.0` to install the most recent version. 

Can you let me know if that works for you?

**Comment by oliverjohns** [comment]
> Hey, [@oliverjohns](https://github.com/oliverjohns). Thanks for the heads up.
> 
> `rasterizehtml`'s `package.json` specifies `inlineresources` as `^1.1.0`, so you should be able to run `npm install inlineresources@1.2.0` to install the most recent version.
> 
> Can you let me know if that works for you?

Updating `inlineresources` to `1.2.0` did not fix the issue for me, same issue with next google font. Someone else is welcome to try.

**Comment by bernardobelchior** [comment]
@oliverjohns could you explain what you are experiencing? Is the download failing? Is the font wrong on the output? 

If you could provide a reproduction it would also help

**Comment by oliverjohns** [comment]
> [@oliverjohns](https://github.com/oliverjohns) could you explain what you are experiencing? Is the download failing? Is the font wrong on the output?
> 
> If you could provide a reproduction it would also help

Im trying to use the `ChartProApi` to download the chart as a PNG:
`apiRef.current?.exportAsImage({ fileName: filename, type: 'image/png', nonce });`

But the export fails with the error below outputted into the console:

```
MUI X Charts: Error exporting chart as image: Error: MUI X Charts: Failed to create blob from canvas.
    exportImage exportImage.js:89
    exportAsImage useChartProExport.js:42
    t1 useChartExport.ts:12
    executeDispatch react-dom-client.development.js:20541
    runWithFiberInDEV react-dom-client.development.js:987
    processDispatchQueue react-dom-client.development.js:20591
    dispatchEventForPluginEventSystem react-dom-client.development.js:21162
    batchedUpdates$1 react-dom-client.development.js:3375
    dispatchEventForPluginEventSystem react-dom-client.development.js:20745
    dispatchEvent react-dom-client.development.js:25671
    dispatchDiscreteEvent react-dom-client.development.js:25639
    addTrappedEventListener react-dom-client.development.js:20692
    listenToNativeEvent react-dom-client.development.js:20627
    listenToAllSupportedEvents react-dom-client.development.js:20640
    listenToAllSupportedEvents react-dom-client.development.js:20637
    hydrateRoot react-dom-client.development.js:30576
    hydrate app-index.tsx:356
    startTransition React
    hydrate app-index.tsx:355
    async* app-next-turbopack.ts:13
    appBootstrap app-bootstrap.ts:79
    loadScriptsInSequence app-bootstrap.ts:23
    appBootstrap app-bootstrap.ts:61
    <anonymous> app-next-turbopack.ts:10
    instantiateModule dev-base.ts:244
    runModuleExecutionHooks dev-base.ts:278
    instantiateModule dev-base.ts:238
    getOrInstantiateRuntimeModule dev-base.ts:128
    registerChunk runtime-backend-dom.ts:57
    registerChunk dev-base.ts:1149
    NextJS 2
```

I have:
- Latest MUI versions
- Latest mui-x versions
- Nonce passed to chart export
- `inlineresources@1.2.0`

**Comment by bernardobelchior** [comment]
Would you be able to create a reproduction? Or do you see any other errors or warnings? 
From that error alone, it isn't clear that the issue is originating in a Content Security Policy.

**Comment by oliverjohns** [comment]
I will see if I can create a reproduction. But regardless of what the problem is, the error message needs to be clarified.

The `MUI X Charts: Error exporting chart as image: Error: MUI X Charts: Failed to create blob from canvas.` is ridiculously unclear and doesnt help in any way shape or form to debug the problem.

**Comment by bernardobelchior** [comment]
> I will see if I can create a reproduction

Thank you.

> the error message needs to be clarified

I agree that the message isn't actionable, but that's unfortunately part of the platform. The error "MUI X Charts: Failed to create blob from canvas." is only thrown when:
1. `HTMLCanvasElement.toBlob` throws, in which case the error contains the error cause
2. `HTMLCanvasElement.toBlob`'s callback is called with `null`, which might happen "if the image cannot be created for any reason" ([source](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob#callback)).

In the first case, we provide the error cause which should help debug the issue. In the latter case there isn't much we can do as there is no information available to us. The only option for us is to rely on error reproductions so we can try to detect them before calling `toBlob`. 

I understand this is frustrating from your side, and we'd like to help, but we're also constrained in this case. Hope you understand and can provide that reproduction so we can fix this issue and detect it earlier!
