### ISSUE TITLE
[charts] XAxis tick labels not showing under certain conditions

### ISSUE THREAD

**Issue by jalzamora-limit** [mui/mui-x#20291]
### Steps to reproduce

After upgrading to version 8.15.0, the BarChart no longer displays xAxis labels on Firefox (https://stackblitz.com/edit/v7awvsrp-ftctxwgs?file=package.json) (Tested on Ubuntu 24.04.3 LTS, Firefox 145.0) 

LineChart seems to also be affected (https://mui.com/x/react-charts/line-demo/)

I've also got an app locally that exhibits this behaviour on both Chromium (142.0.7444.59) and Firefox, but I haven't been able to replicate it on a Stackblitz environment.

### Current behavior

xAxis labels are missing.
<img width="1488" height="605" alt="Image" src="https://github.com/user-attachments/assets/dcb1dd72-ada4-4aed-9baf-b109af33d217" />

<img width="1003" height="522" alt="Image" src="https://github.com/user-attachments/assets/7a28e329-6d7d-4ecd-82be-cada94f53a26" />

### Expected behavior

On the previous version (8.14.1) and on Chromium they are shown correctly.
<img width="1484" height="632" alt="Image" src="https://github.com/user-attachments/assets/fa14caeb-4714-4b55-8e05-ad043d5504a8" />

<img width="944" height="516" alt="Image" src="https://github.com/user-attachments/assets/7494c0cc-ea32-4339-b546-352b909a04f2" />

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 6.14 Ubuntu 24.04.3 LTS 24.04.3 LTS (Noble Numbat)
  Binaries:
    Node: 23.1.0 - /home/arteux/.nvm/versions/node/v23.1.0/bin/node
    npm: 10.9.0 - /home/arteux/.nvm/versions/node/v23.1.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Firefox: 145.0
  npmPackages:
    @emotion/react: ^11.14.0 => 11.14.0 
    @emotion/styled: ^11.14.1 => 11.14.1 
    @mui/core-downloads-tracker:  7.3.4 
    @mui/icons-material: ^7.3.4 => 7.3.4 
    @mui/material: ^7.3.4 => 7.3.4 
    @mui/private-theming:  7.3.3 
    @mui/styled-engine:  7.3.3 
    @mui/system:  7.3.3 
    @mui/types:  7.4.7 
    @mui/utils:  7.3.3 
    @mui/x-charts: ^8.16.0 => 8.16.0 
    @mui/x-charts-vendor:  8.15.0 
    @mui/x-data-grid:  8.16.0 
    @mui/x-data-grid-pro: ^8.16.0 => 8.16.0 
    @mui/x-date-pickers: ^8.16.0 => 8.16.0 
    @mui/x-internal-gestures:  0.3.4 
    @mui/x-internals:  8.16.0 
    @mui/x-license:  8.16.0 
    @mui/x-telemetry:  8.16.0 
    @mui/x-virtualizer:  0.2.6 
    @types/react: ^19.2.2 => 19.2.2 
    react: ^19.2.0 => 19.2.0 
    react-dom: ^19.2.0 => 19.2.0 
    typescript: ~5.9.3 => 5.9.3 
```
</details>

**Search keywords**: charts bar BarChart firefox xAxis tick ticklabel label

**Comment by bernardobelchior** [comment]
Hey, @jalzamora-limit. This happens because the axis height isn't big enough to display the labels in the given font. If you tweak the `xAxis.height` property does this keep happening? I'm not able to reproduce what you're seeing, but I'm running macOS, not Ubuntu.

**Comment by michaljusiega** [comment]
I have the same issue since `8.15.0 mui/x-charts` on Windows and Firefox/Chrome.

`xAxis.height` property not exists compared to `yAxis.width`

If `disableTicks` is set to `true`, then labels are showing.

**Comment by bernardobelchior** [comment]
Hey, @michaljusiega, do you have a reproduction of the issue? Is it the same demo?

Also, `xAxis.height` should exist ([docs](https://mui.com/x/api/charts/axis-config/#axis-config-prop-height)). What are you experiencing that lead you to believe it doesn't?

**Comment by michaljusiega** [comment]
No, I don't have any reproducer. I'm amateur in react/mui. :(

This is how I see a demo page: 

<img width="2558" height="1201" alt="Image" src="https://github.com/user-attachments/assets/e680e188-f5b6-45db-8c18-ef7ad2182b76" />

**Comment by bernardobelchior** [comment]
I see. That's because our default height for the axis doesn't work for all operating systems apparently. Thanks for reporting. We'll fix it 👍

**Comment by michaljusiega** [comment]
Thank you very much!

**Comment by jalzamora-limit** [comment]
I don't think this is solely caused by a height issue. When I inspect the DOM on Chromium, I can see the label text inside the SVG element.

<img width="1016" height="572" alt="Image" src="https://github.com/user-attachments/assets/eaad091c-6f03-4956-8c7c-344aac3b2050" />

However, in Firefox the tspan element appears empty:

<img width="965" height="726" alt="Image" src="https://github.com/user-attachments/assets/b51e9eeb-34af-49bd-994d-d7ce04b341a4" />

If I manually change the text content, it displays correctly. Meaning that in my case the issue doesn't seem to be the height, but that the label itself is not being set correctly.

**Comment by bernardobelchior** [comment]
Hey, @jalzamora-limit! That's normal. We measure the label size and don't render it if it wouldn't fit. So it does point to an issue with the default height. If you increase the x-axis height, does it fix it the issue? If so, it's confirmation that this is indeed the root cause.

**Comment by jalzamora-limit** [comment]
My bad, you’re completely right!

In my case, the label only shows when using a height of 29 or higher.
<img width="910" height="674" alt="Image" src="https://github.com/user-attachments/assets/6d8fa08d-d238-4aea-9022-f65800b4b90f" />

**Comment by bernardobelchior** [comment]
Thanks for confirming. We'll increase the height to ensure it's visible on your environment as well.

**Comment by JCQuintas** [comment]
When [[charts] Use getBBox() for correct SVG sizes in firefox #20309](https://github.com/mui/mui-x/pull/20309) is released somewhere next week, it should fix the issues seen on Firefox on both Windows and Linux.

**Comment by jalzamora-limit** [comment]
The issue is still happening for me, although it's more rare now.
The demo in the docs shows up correctly, but if I open it on stackblitz without any modification, the xAxis dissappears:
https://stackblitz.com/edit/5sodu25b?file=src%2FDemo.tsx

<img width="1659" height="701" alt="Image" src="https://github.com/user-attachments/assets/726683c4-9c9d-4d2a-a0e8-57620548c7e0" />

Maybe it's some kind of rounding error when calculating the height?
If I put the page on the minimum zoom level (30%) on Firefox and I refresh the page (https://mui.com/x/react-charts/bar-demo/), even if I put the zoom level back to 100%, the labels are still hidden.

A way I found to replicate this in Chromium is to change the fontFamily (Noto sans in my case) https://stackblitz.com/edit/cq5fte21-dmrdlcfv?file=src%2FDemo.tsx. When using that font, the xAxis won't show correctly, even on Chromium.

**Comment by JCQuintas** [comment]
Hi @jalzamora-limit thanks for the feedback. I wasn't able to reproduce it on Windows/OSX, but I saw you are using Linux. 

I'll check in that OS and report back.

**Comment by JCQuintas** [comment]
I've reopened it as I can reproduce on Ubuntu on Firefox in some specific instances as @jalzamora-limit mentioned

**Comment by michaljusiega** [comment]
But for me, I can confirm that https://github.com/mui/mui-x/pull/20309 and 8.19 release resolved this issue. Very weird ;)

**Comment by Paul6552** [comment]
I have the same problem with lineCharts, but only with lineCharts. BarChart for example works :-/
Chrome latest version, Linux Mint latest, mui x latest version

**Comment by bernardobelchior** [comment]
Hey, @Paul6552. Does this happen on the MUI X Docs or another website? If the latter, is the tick label font family being customized? 

If you could provide a reproduction we'd be happy to look into it

**Comment by cs-stainly** [comment]
@bernardobelchior this problem with various types of charts can be observed on https://mui.com/x/react-charts/examples/

Firefox (146.0.1 64-bit; Ubuntu):
<img width="839" height="516" alt="Image" src="https://github.com/user-attachments/assets/b45cdd41-2293-49ad-955f-2325c982e8c5" />

Chromium (143.0.7499.169 (Official Build) snap (64-bit); Ubuntu):
<img width="834" height="501" alt="Image" src="https://github.com/user-attachments/assets/1ac2345b-85a0-4e85-a050-df8ddcc3072b" />

**Comment by bernardobelchior** [comment]
Thanks, @cs-stainly! Opened #20844 to fix all the examples on Firefox in Ubuntu
