### ISSUE TITLE
[data grid] Broken "stop editing" integration with IME e.g. Japanese

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-x#2338]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

IME keys are not processed correctly

## Expected Behavior 🤔

IME keys are processed correctly

## Steps to Reproduce 🕹

Steps:

1. Open https://material-ui.com/components/data-grid/editing/#cell-editing
2. See how pressing <kbd>Enter</kbd> shouldn't exit the edit mode. The end-user isn't done yet.

https://user-images.githubusercontent.com/3165635/129441582-174bd4d5-b13d-477f-9d87-e7bacdf7ce3a.mp4

The same happens with <kbd>Escape</kbd>.

version 4.0.0-alpha.38

## Context 🔦

We saw this request by email:

> I bought and use xgrid and am trying to figure out Japanese IME composition in x-grid.

> When I type Japanese in a cell, typing Japanese letters and converting them into Chinese character (Kanji) for example, it ends composition and goes to next cell.

> Is there any good way not to finish the composition session. I believe people use onCompositionEnd, onCompositionStart and onCompositionUpdate but you are only able to use them in <input>, not <datagrid>

https://github.com/mui-org/material-ui/issues/23044
https://github.com/mui-org/material-ui/issues/19435
https://github.com/mui-org/material-ui/pull/19499
https://github.com/mui-org/material-ui/pull/23050

Sometimes, I feel that we should kill the x@mui.com email to force all communications to happen on GitHub cc @mui-org/x & @mbrookes

**Comment by oliviertassinari** [comment]
This is an easy one to fix:

```diff
diff --git a/packages/grid/_modules_/grid/hooks/features/rows/useGridEditRows.ts b/packages/grid/_modules_/grid/hooks/features/rows/useGridEditRows.ts
index 9de65f42..a6f97119 100644
--- a/packages/grid/_modules_/grid/hooks/features/rows/useGridEditRows.ts
+++ b/packages/grid/_modules_/grid/hooks/features/rows/useGridEditRows.ts
@@ -250,6 +250,12 @@ export function useGridEditRows(
         apiRef.current.commitCellChange({ id, field }, event);
         apiRef.current.publishEvent(GridEvents.cellEditStop, params, event);
       }
+
+      // Wait until IME is settled.
+      if (event.which === 229) {
+        return;
+      }
+
       if (isEditMode && isCellEditCommitKeys(event.key)) {
         const commitParams = { id, field };
         if (!apiRef.current.commitCellChange(commitParams, event)) {
```

However, I didn't work on it because it would likely conflict with #2098. For the test cases, a quick simple one is probably enough.

**Comment by taeslee** [comment]
Hi @oliviertassinari,

I would like to work on this issue. Can you assign me to this issue?

**Comment by flaviendelangle** [comment]
Here you are :+1:

**Comment by taeslee** [comment]
It seems like this issue was already resolved.
https://user-images.githubusercontent.com/64485716/134408162-295b170c-e053-4857-be7e-484d71473264.mp4

https://user-images.githubusercontent.com/64485716/134413111-16152533-fcee-4e40-a88a-8d2f1a475fae.mp4

**Comment by oliviertassinari** [comment]
I have just tried on https://mui.com/components/data-grid/editing/#cell-editing, it's still broken for me on macOS.

**Comment by guoyunhe** [comment]
I developed a similar React component in Alibaba. The way I find to support IME is to always mount an `<input>` with focus. When it is inactive, just set opacity to hide it.

In DataGrid, when users type "wo" in IME, "w" is always inserted as it is because here is no `<input/>` when users type "w", so the IME cannot spell "我". Mounting an invisible `<input/>` will solve the issue.

**Comment by alepuente** [comment]
Hello guys, I am having the same issue. Is there any solution to this?

**Comment by alepuente** [comment]
@guoyunhe Is there any code example you can show me?

**Comment by alepuente** [comment]
Hello guys, 
I have the same problem but i cant find any solution.
The issue i am having is with InputBase.
As you can see in this video after entering some charachters I press the cancell button on the right.
As desired the text gets errased and the focus on the input gets lost.
But after that no matter where I click, the input gets focused again.

https://user-images.githubusercontent.com/20970908/160828096-68db36df-1dae-4c3c-9a6b-44ccdfcec040.MOV

**Comment by oliviertassinari** [comment]
I have just tested this on AG Grid's live demo, they don't support it. The bug was reported in https://github.com/ag-grid/ag-grid/issues/4435.
