### ISSUE TITLE
[data-grid] Resize performance and `renderCell` calls

### ISSUE THREAD

**Issue by macnaughton** [mui/mui-x#3894]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When resizing the window or taking action that resized the DataGrid component, animation stutters and `renderCell` functions are called excessively.

### Expected behavior 🤔

Smoother animation and fewer calls to `renderCell`

### Steps to reproduce 🕹

Steps:

1.  Set up a trivial DataGrid with a with a column using `renderCell` to generate the column's value
2.  Resize the window, or in my case, open/close a sidebar and the animation stutters

To simplify I've created 2 codesandboxes; 1 using the v4.x DataGrid component, and one using the v5.x component.  The issue is not present in the v4 version, only the v5.  It's not cery scientific, but if you open the code sandbox and resize the "browser" view you'll see the calls in `renderCell` being logged to the console.  You'll notice that the call count in the v5 version is far greater than the v4 version.  I suspect this is what's causing animation stuttering on when open/closing the sidebar (an action that causes the table to resize).

v5 Sandbox:  https://codesandbox.io/s/datagriddemo-rendercell-call-count-v5-9u36r?file=/demo.tsx
v4 Sandbox:  https://codesandbox.io/s/datagriddemo-rendercell-call-count-v4-xdj36?file=/src/App.tsx

### Context 🔦

I'm attempting to improve performance when using the DataGrid component with custom renderCell functions.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
 System:
    OS: macOS 12.1
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - ~/node_modules/.bin/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Edge: Not Found
    Firefox: 96.0.3
    Safari: 15.2
  npmPackages:
    @emotion/react: 11.7.1 => 11.7.1 
    @emotion/styled: 11.6.0 => 11.6.0 
    @mui/base:  5.0.0-alpha.65 
    @mui/icons-material: 5.3.0 => 5.3.0 
    @mui/lab: 5.0.0-alpha.65 => 5.0.0-alpha.65 
    @mui/material: 5.3.0 => 5.3.0 
    @mui/private-theming:  5.3.0 
    @mui/styled-engine:  5.3.0 
    @mui/system:  5.3.0 
    @mui/types:  7.1.0 
    @mui/utils:  5.3.0 
    @mui/x-data-grid: 5.3.0 => 5.3.0 
    @types/react: 17.0.38 => 17.0.38 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    typescript: 4.5.5 => 4.5.5 

```

Tested in Chrome and FireFox
</details>

**Comment by macnaughton** [comment]
@cherniavskii Thanks for checking.  I'll see about putting together a better sandbox example.  meanwhile, I just reopened the sansboxes and resized the browser view and see more calls to `renderCell` in v5 than in v4.  I'll attempt to drop in a couple screen recordings below:

V4:
https://user-images.githubusercontent.com/11035430/153065581-ac174ff0-8670-46a7-97b0-267345f4e785.mp4

V5:
https://user-images.githubusercontent.com/11035430/153065603-0fcf6abe-255e-4075-97de-3e54c067e302.mp4

The issue I'm having is when I have a sidebar that slides out (navigation) that resizes the main content area (thus forcing the DataGrid to recalculate size I'm getting stutter in the sidebar animation.  It gets worse if I have a DataGrid with more columns/renderCell functions.  I'm currently updating a project from MUI v4 to v5 and this did not seem to be an issue in v4.  I hope this helps, please let me know if you need more information.

**Comment by macnaughton** [comment]
Here's a couple updated sandboxes:

v5: 
https://codesandbox.io/s/datagriddemo-rendercell-call-count-v5-forked-gbk73?file=/demo.tsx

v4:
https://codesandbox.io/s/datagriddemo-rendercell-call-count-v4-forked-2u9wp?file=/src/App.tsx

It's pretty basic, but clicking the "toggle" button will trigger a trivial animation.  In each sandbox the call count to `renderCell` is getting logged out and you'll see that it's much higher in v5 vs v4.  Animation stutter isn't completely apparent here because I'm attempting to keep the examples simple.  I hope this helps.

**Comment by cherniavskii** [comment]
@macnaughton Thanks for the reproduction!
I've turned CPU throttling and I can see that v4 is smoother that v5.
Also, it looks like v5 calls `renderCell` on each `resize` event, while v4 calls `renderCell` only after sidebar is fully expanded or collapsed.
Toggling sidebar twice ends up with:
- 1907 `renderCell` calls in v5
- 94 `renderCell` calls in v4

**Comment by flaviendelangle** [comment]
Maybe something wrong with the [debouncing](https://github.com/mui/mui-x/blob/master/packages/grid/_modules_/grid/hooks/features/dimensions/useGridDimensions.ts#L189)

**Comment by flaviendelangle** [comment]
I see two reasons why `useGridVirtualScroller` is triggered on each frame during resizing

1. We listen do `GridEvents.resize` instead of `GridEvents.debouncedResize` to update the container width
2. `GridAutoSizer` rerenders on each frame and causes it's children (`DataGridProVirtualScroller` or `DataGridVirtualScroller`) to re-render

**Comment by cgarrovillo** [comment]
Can confirm that this is still an issue on 5.6.2

**Comment by flaviendelangle** [comment]
@m4theushw maybe you'll know better how to improve the virtualization

**Comment by hikotq** [comment]
Is there a workaround?

**Comment by m4theushw** [comment]
By comparing with v4, I found 3 improvements we can do to reduce the number of rerenders:

1. Listen to `debouncedResize` instead of `resize`, like pointed in https://github.com/mui/mui-x/issues/3894#issuecomment-1046897354

    I used `resize` in v5 because I wanted to avoid showing a scrollbar when resizing. In the v4 demo you can see the scrollbar appearing and disappearing after the animation finishes. However, v5 also added `overflow: auto` later, only when the width of the columns don't generate scrollbar, so it's safe to use the debounced version now.

    ```diff
    diff --git a/packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx b/packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx
    index b71c895f6..20e985595 100644
    --- a/packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx
    +++ b/packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx
    @@ -210,13 +210,13 @@ export const useGridVirtualScroller = (props: UseGridVirtualScrollerProps) => {
         setContainerWidth(rootRef.current!.clientWidth);
       }, [rowsMeta.currentPageTotalHeight]);
     
    -  const handleResize = React.useCallback<GridEventListener<'resize'>>(() => {
    +  const handleResize = React.useCallback<GridEventListener<'debouncedResize'>>(() => {
         if (rootRef.current) {
           setContainerWidth(rootRef.current.clientWidth);
         }
       }, []);
     
    -  useGridApiEventHandler(apiRef, 'resize', handleResize);
    +  useGridApiEventHandler(apiRef, 'debouncedResize', handleResize);
     
       const updateRenderZonePosition = React.useCallback(
         (nextRenderContext: GridRenderContext) => {
    ```

2. Memoize `GridRow`

    In v4, the old `GridRowCells` was memoized and it prevented rerendering the cells if props don't change. In v5, `React.memo` was removed because it's useless since `renderedColumns` changes on every rerender. We can add it back if we do 3 too.

    ```diff
    diff --git a/packages/grid/x-data-grid/src/components/GridRow.tsx b/packages/grid/x-data-grid/src/components/GridRow.tsx
    index d6eb783d6..bf1437539 100644
    --- a/packages/grid/x-data-grid/src/components/GridRow.tsx
    +++ b/packages/grid/x-data-grid/src/components/GridRow.tsx
    @@ -439,4 +439,6 @@ GridRow.propTypes = {
       visibleColumns: PropTypes.arrayOf(PropTypes.object).isRequired,
     } as any;
     
    -export { GridRow };
    +const MemoizedRow = React.memo(GridRow);
    +
    +export { MemoizedRow as GridRow };
    ```

3. Cache `renderedColumns` using `firstColumnToRender` and `lastColumnToRender` as keys

    `React.memo` won't work unless we fix `renderedColumns` to return the same value if the bounds don't change. Currently, in every rerender it generates a new value.

    https://github.com/mui/mui-x/blob/38ba9cad0586136db103404027053358f1c77034/packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx#L414

I implemented these 3 improvements in a rudimentary way in my local environment and the results showed a considerable improvement in the number of calls to `renderCell`.

**Comment by jarb99** [comment]
Hi there,

We are seeing the same issues with v5.15.2 relating to sidebar / window resize events causing CPU spike and jerky transitions.

I wonder whether a workaround could be achieved similar to the tabulator 'block redraw' workaround? [http://tabulator.info/docs/5.3/layout#virtual-dom-redraw](url). I have used this approach in the past to resolve jerky animation when resizing during a sidebar open or window resize event using a hook with success. During a sidebar open or window resize the user will not be interacting with the datagrid so we found this workaround was a practical solution to get 100% smooth transition animation.

**Comment by Duderinooo** [comment]
Hey there. 
I am currently facing the same issue. I have multiple columns with renderCell containing custom components/images. I have a sidebar that I open, and I control the animation there with framer motion. The default animation is really laggy on dev env and gets slightly better on prod. Setting rowBuffer to ={1} helped already with some performance gains. What helped significantly was the use of a useMemo for my column arrays. 

What I can also see is that I get about 300-400 calls for a single renderCell while expanding the sidebar. Closing the sidebar has significantly less calls.

**Comment by cherniavskii** [comment]
https://github.com/mui/mui-x/pull/7864 should fix it in v6

**Comment by yannours** [comment]
Hey guys, we actually update in v6 and the problem is still here.

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) might be a good starting point.

For this amount of cells, the performance you are describing are clearly not normal.

**Comment by yannours** [comment]
Hi, https://codesandbox.io/s/data-grid-community-forked-j9eco9?file=/src/App.tsx there it is !

You toggle the button and it pop in a div taht cause the datagrid to rerender a lot lot of times (it's even worst on our side).
I find out that it's about override theGrid Main width in % that trigger an unwanted behaviour to resize multiple time until it finally get the correct size, which is weird because it should be done in 2 iteration as it's done when the div pop out (toggle the button again).

regards,
