### ISSUE TITLE
[data-grid] Proptype warning when providing "invalid" `formattedValue` or `value` to `GridCell`

### ISSUE THREAD

**Issue by sharashka-io** [mui/mui-x#4324]
### Order ID 💳

#39955

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Using @mui 5.5.3 and @mui/x-data-grid-pro 5.7.0, we see the following errors when rendering a grid:

```
Warning: Failed prop type: Invalid prop `formattedValue` supplied to `GridCell`, expected one of type [number, object, string, boolean].
    at GridCell (webpack-internal:///./node_modules/@mui/x-data-grid/components/cell/GridCell.js:73:5)
    at GridRow (webpack-internal:///./node_modules/@mui/x-data-grid/components/GridRow.js:87:5)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
    at GridVirtualScrollerRenderZone (webpack-internal:///./node_modules/@mui/x-data-grid/components/virtualization/GridVirtualScrollerRenderZone.js:49:5)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
    at GridVirtualScrollerContent (webpack-internal:///./node_modules/@mui/x-data-grid/components/virtualization/GridVirtualScrollerContent.js:47:5)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
    at GridVirtualScroller (webpack-internal:///./node_modules/@mui/x-data-grid/components/virtualization/GridVirtualScroller.js:49:5)
    at DataGridProVirtualScroller (webpack-internal:///./node_modules/@mui/x-data-grid-pro/components/DataGridProVirtualScroller.js:136:99)
    at div
    at AutoSizer (webpack-internal:///./node_modules/@mui/x-data-grid/components/GridAutoSizer.js:26:5)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
    at GridMainContainer (webpack-internal:///./node_modules/@mui/x-data-grid/components/containers/GridMainContainer.js:42:100)
    at GridBody (webpack-internal:///./node_modules/@mui/x-data-grid/components/base/GridBody.js:34:5)
    at ErrorBoundary (webpack-internal:///./node_modules/@mui/x-data-grid/components/ErrorBoundary.js:8:1)
    at GridErrorHandler (webpack-internal:///./node_modules/@mui/x-data-grid/components/base/GridErrorHandler.js:29:5)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
    at NoSsr (webpack-internal:///./node_modules/@mui/base/NoSsr/NoSsr.js:26:5)
    at GridRoot (webpack-internal:///./node_modules/@mui/x-data-grid/components/containers/GridRoot.js:42:100)
    at GridContextProvider (webpack-internal:///./node_modules/@mui/x-data-grid/context/GridContextProvider.js:16:3)
    at DataGridPro (webpack-internal:///./node_modules/@mui/x-data-grid-pro/DataGridPro/DataGridPro.js:33:90)
    [...]
```

followed by the very similar

```
Warning: Failed prop type: Invalid prop `value` supplied to `GridCell`, expected one of type [number, object, string, boolean].
    at GridCell (webpack-internal:///./node_modules/@mui/x-data-grid/components/cell/GridCell.js:73:5)
    at GridRow (webpack-internal:///./node_modules/@mui/x-data-grid/components/GridRow.js:87:5)
    at div
    [...]
```

Apart from the console warning, this does not actually appear to affect functionality in any obvious way.

If it is relevant, we are using the master detail feature.

We are also using NextJS (12.1.4).

I suspect this is a bug in our usage of the data grid, rather than a bug in the data grid itself, but I'm stumped as to where to start looking for the issue. Could you offer any advice? Thanks in advance!

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Linux 5.15 Ubuntu Jammy Jellyfish (development branch) 22.04 (Jammy Jellyfish)
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: Not Found
    npm: 8.5.3 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 100.0.4896.60
    Firefox: 98.0.2
  npmPackages:
    @emotion/react: ^11.8.2 => 11.8.2 
    @emotion/styled: ^11.8.1 => 11.8.1 
    @mui/base:  5.0.0-alpha.74 
    @mui/icons-material: ^5.5.1 => 5.5.1 
    @mui/lab: ^5.0.0-alpha.75 => 5.0.0-alpha.75 
    @mui/material: ^5.5.3 => 5.5.3 
    @mui/private-theming:  5.5.3 
    @mui/styled-engine:  5.5.2 
    @mui/system: ^5.5.3 => 5.5.3 
    @mui/types:  7.1.3 
    @mui/utils:  5.5.3 
    @mui/x-data-grid:  5.7.0 
    @mui/x-data-grid-pro: ^5.7.0 => 5.7.0 
    @mui/x-license-pro:  5.7.0 
    @types/react: ^17.0.43 => 17.0.43 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.6.3 => 4.6.3 

Issue occurs when using both Chrome and Firefox.
```
</details>

**Comment by flaviendelangle** [comment]
Hi

It should be fixed by #4064 which should be released at the beginning of next week.
Before, our typing only supported some formats for the `value` and `formattedValue`, which makes no sense because if should be able to use any format of data in your cells.

**Comment by sharashka-io** [comment]
Thanks Flavien, we will upgrade when the new version is available. Happy mui-x customers here!

**Comment by ETN-Tech** [comment]
I have the same problem. It seems that GridCell don't accept array as formattedValue. 

**Proposed solution**
Adding array type in props validation of GridCell should correct the error. 🙂

**Comment by flaviendelangle** [comment]
As written above, the next version should fix the problem

**Comment by MorMeshulam** [comment]
i just upgraded from 5.7.0 to 5.17.9 and still getting this error.
i found that this issue is related to this error msg -> 
"Failed prop type: Invalid prop `value` supplied to `GridCell`, expected one of type [number, object, string, boolean]"

not sure i understand from where this error warning is coming from.

from wrong data ? (unsupported value types - i send undefined sometimes)
from a formatter ? (i dont use formatting) 
i am using renderCell for all cells
i am using custom row component.

any help?
