### ISSUE TITLE
[DatePicker] DatePicker rendered on server has `readOnly` true

### ISSUE THREAD

**Issue by PetroSilenius** [mui/mui-x#4845]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When pre-rendering a page with DatePicker component the datepicker is rendered as readOnly. After the first client side render the picker loses the readOnly prop.

### Expected behavior 🤔

The DatePicker input should have readOnly false by default also when rendered on the server

### Steps to reproduce 🕹

Here's a Stackblitz example with debugger ready to go https://stackblitz.com/edit/nextjs-bal7gc?file=pages/index.js
Steps:

1. Open Stackblitz preview in a new window
2. Refresh page
3. Inspect pre-rendered DOM to find the DatePicker's underlying input element with id `text-field`
4. Input element has readOnly

### Context 🔦

The bug is causing issues on our Cypress E2E tests since it interacts on mostly the pre-rendered DOM.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Browser Chrome 98.0
  System:
    OS: macOS 12.2.1
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Edge: Not Found
    Firefox: Not Found
    Safari: Not Found
  npmPackages:
    @emotion/react: ^11.7.1 => 11.7.1
    @emotion/styled: ^11.6.0 => 11.6.0
    @mui/base:  5.0.0-alpha.68
    @mui/lab:  5.0.0-alpha.68
    @mui/material: ^5.4.1 => 5.4.1
    @mui/private-theming:  5.4.1
    @mui/styled-engine:  5.4.1
    @mui/styles:  5.4.1
    @mui/system:  5.4.1
    @mui/types:  7.1.1
    @mui/utils:  5.4.1
    @mui/x-data-grid:  5.5.1
    @types/react: ^17.0.38 => 17.0.39
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
    typescript: ^4.5.4 => 4.5.5
```
</details>

**Comment by flaviendelangle** [comment]
The problem is that on the server, we don't know if the picker is in mobile or desktop mode.
And by default, we render the mobile mode where `readOnly: true` on the input. 

There is no perfect solution here, since, by definition we don't know for sure if we should render the desktop or mobile version on the server.

Our `useMediaQuery` hook has options to decide what to do on the server (see [this section on the doc])

But it would be better if the picker input was 100% identically between mobile and desktop to avoid this problem.
Maybe we could remove the `readOnly` on mobile and use another solution to have this non-editable input (block events for instance).

**Comment by PetroSilenius** [comment]
Thanks for your reply @flaviendelangle! Seems like the link to `useMediaQuery` docs is missing from your comment but I guess you meant to [this section](https://mui.com/material-ui/react-use-media-query/#server-side-rendering)?

Removing the `readOnly` on mobile and blocking events sounds like a valid way to approach

**Comment by LukasTy** [comment]
Accepting #5684 would probably solve your issue @PetroSilenius as pickers would default to rendering desktop version when unable to decide based on `matchMedia` availability.
Unless @flaviendelangle would disagree with this change. 🤔

**Comment by LukasTy** [comment]
@PetroSilenius Could you check if the [newest release](https://www.npmjs.com/package/@mui/x-date-pickers/v/5.0.0-beta.5) resolves your issue?

**Comment by PetroSilenius** [comment]
Seems like so, created a fork of the Stackblitz example in the issue and changed to` x-date-pickers` version `5.0.0-beta.5`
https://stackblitz.com/edit/nextjs-agrycl

It does now render the desktop version on the server and doesn't have the readonly value by default. Nice work LukasTy!

**Comment by saewitz** [comment]
We have the same problem on v5.0.10 and v6.18.6. We fixed it with the suggestion in microsoft/playwright#7769

```
firefox.launch({
    firefoxUserPrefs: {
        "ui.primaryPointerCapabilities": 0x02 | 0x04,
        "ui.allPointerCapabilities": 0x02 | 0x04,
    },
});
```

**Comment by HJK181** [comment]
I'm still facing the issue in my Cypress e2e test running version: @mui/x-date-pickers-pro": "^6.19.12

**Comment by FleMo93** [comment]
As found in the [mui-x react-date-pickers documentation](https://mui.com/x/react-date-pickers/base-concepts/#testing-caveats) which leadts to [a usefull comment](https://github.com/microsoft/playwright/issues/7769#issuecomment-1205106311) setting the launch option as mentioned in the comment helped for the cypress e2e tests.

Here the required part of the cypress.config.ts (we currently only test chrome):
```ts
import { defineConfig } from 'cypress';
export default defineConfig({
  viewportWidth: 1280,
  viewportHeight: 800,
  chromeWebSecurity: false,
  numTestsKeptInMemory: 10,
  defaultBrowser: 'chrome',
  e2e: {
    baseUrl: 'http://localhost:3000',
    supportFile: 'cypress/support/index.js',
    setupNodeEvents(on, config) {
      on('before:browser:launch', (browser, launchOptions) => {
        console.log('Cypress browser:', browser);
        if (browser.family === 'chromium') {
          launchOptions.args.push('--blink-settings=primaryPointerType=4');
        }
        return launchOptions;
      });
      return config;
    },
  },
});
```
