### ISSUE TITLE
[data grid] Filter panel breaks layout on small display

### ISSUE THREAD

**Issue by bruceharrison1984** [mui/mui-x#5183]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Opening the filter panel on a small display breaks the layout on the X axis.

![Screenshot_20220612-160534](https://user-images.githubusercontent.com/17836372/173253605-0e09d02d-0ac4-45e0-a108-5943d127bb9e.png)

### Expected behavior 🤔

I'd expect the filter panel to honor the page layout and not break out beyond the expected page bounds. 

### Steps to reproduce 🕹

Steps:

1. Open filter panel on a mobile device, when the DataFrid is assigned full width. 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
A workaround could be to limit the width of the panel:
```jsx
componentsProps={{ filterPanel: { sx: { maxWidth: "100vw" } } }}
```

https://codesandbox.io/s/datagriddemo-demo-mui-x-forked-4t90kx?file=/demo.tsx

I don't see a good behavior for the filter panel on small screen

**Comment by bruceharrison1984** [comment]
@alexfauquette Thanks for the workaround, this'll get me unstuck at least in the near-term. I agree that the current panel layout won't gracefully perform on a smaller screen, and it'd likely need to be reflowed in a more vertical-centric way in order to improve UX.

Thanks 👍

**Comment by gerdadesign** [comment]
Should these elements stack vertically past a certain breakpoint? (Do we have existing breakpoints already defined?)

**Comment by alexfauquette** [comment]
Mo, for now, the sizes are fixed except for the "value" input which can be customized by dev. The filter panel itself only have a min width

**Comment by jacobcarrington** [comment]
Surprised to see this is still an issue in version 6. My work around as it effects all DataGrids is to update the theme `defaultProps`. 

```
const theme: ThemeOptions = {
 ...
  components: {
    MuiDataGrid: {
      defaultProps: {
        slotProps: {
          panel: {
            sx: {
              "& .MuiDataGrid-panelWrapper": {
                maxWidth: "calc(100vw - 4rem)",
              },
            },
          },
        },
      },
    },
  },
};
```

**Comment by cherniavskii** [comment]
We can adopt this workaround in the data grid since it's better than the current behavior anyway 👍
