### ISSUE TITLE
[data grid] Virtual scroller covers NoRowsOverlay

### ISSUE THREAD

**Issue by TeoTN** [mui/mui-x#5725]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When a component is passed to `NoRowsOverlay` slot, it will be covered by a div `.MuiDataGrid-virtualScroller` that prevents any interaction with it

### Expected behavior 🤔

Users should be able to define `NoRowsOverlay` that contains a call to action button that is clickable and not covered by virtual scroller

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/mui-x-norowsoverlay-bug-lwlcos?file=/src/App.tsx

### Context 🔦

Usually when no resources are found, it's a good UX practice to allow creating them in the same place where the message is located

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 12.4
  Binaries:
    Node: 18.4.0 - ~/.nvm/versions/node/v18.4.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.4.0/bin/yarn
    npm: 8.13.2 - ~/.nvm/versions/node/v18.4.0/bin/npm
  Browsers:
    Chrome: Not Found
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.5
  npmPackages:
    @emotion/react: 11.9.3 => 11.9.3
    @emotion/styled: 11.9.3 => 11.9.3
    @mui/base:  5.0.0-alpha.92
    @mui/icons-material: 5.8.4 => 5.8.4
    @mui/lab: 5.0.0-alpha.93 => 5.0.0-alpha.93
    @mui/material: 5.9.3 => 5.9.3
    @mui/private-theming:  5.9.3
    @mui/styled-engine:  5.8.7
    @mui/styles: 5.9.3 => 5.9.3
    @mui/system: 5.9.3 => 5.9.3
    @mui/types:  7.1.5
    @mui/utils:  5.9.3
    @mui/x-data-grid: 5.15.1 => 5.15.1
    @mui/x-date-pickers: 5.0.0-beta.4 => 5.0.0-beta.4
    @types/react: 18.0.14 => 18.0.14
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 4.7.4 => 4.7.4
```
</details>

**Comment by m4theushw** [comment]
Duplicate of #5590 

It's not the `.MuiDataGrid-virtualScroller` div that covers the overlay, but the overlay wrapper that has `pointerEvents: none`. #5674 will fix this.

**Comment by cherniavskii** [comment]
Hey @TeoTN 
Thanks for opening the issue!

We had a regression recently that disabled user events for custom overlays - https://github.com/mui/mui-x/issues/5590
It was fixed by https://github.com/mui/mui-x/pull/5674 and the fix will be included in the next release this week.

After it's released, it will be possible to make it work with some custom styles applied to the overlay:
```tsx
noRowsOverlay: {
  style: {
    position: "relative",
    zIndex: 1
  }
}
```
Here's a working demo (it's using unreleased version of data grid package):
https://codesandbox.io/s/mui-x-norowsoverlay-bug-forked-v3jhso?file=/src/App.tsx:450-705

In the meantime, I will work on improving overlays layout to make the above workaround unnecessary.

**Comment by sampathkumarm** [comment]
> Hey @TeoTN Thanks for opening the issue!
> 
> We had a regression recently that disabled user events for custom overlays - #5590 It was fixed by #5674 and the fix will be included in the next release this week.
> 
> After it's released, it will be possible to make it work with some custom styles applied to the overlay:
> 
> ```tsx
> noRowsOverlay: {
>   style: {
>     position: "relative",
>     zIndex: 1
>   }
> }
> ```
> 
> Here's a working demo (it's using unreleased version of data grid package): https://codesandbox.io/s/mui-x-norowsoverlay-bug-forked-v3jhso?file=/src/App.tsx:450-705
> 
> In the meantime, I will work on improving overlays layout to make the above workaround unnecessary.

@cherniavskii ,
I tried this https://codesandbox.io/s/mui-x-norowsoverlay-bug-forked-t4ivxb?file=/src/App.tsx, but it still does not work. Can you please suggest?

**Comment by GNARGNARDAVE** [comment]
This is still an issue...

**Comment by GNARGNARDAVE** [comment]
MuiDataGrid-virtualScroller has a height of 100% which isn't honored. if it's set to not percent, it works.

**Comment by cherniavskii** [comment]
@GNARGNARDAVE Could you open a new issue with a reproduction example? Thanks!

**Comment by GNARGNARDAVE** [comment]
Actually - I put in a hack - there is no minimum height. This fixes the issue.

.MuiDataGrid-virtualScroller {
  min-height: 100px;
}
