### ISSUE TITLE
[TimePicker] Backspace doesn't work in the TimePicker when a default date value is provided

### ISSUE THREAD

**Issue by Asghwor** [mui/mui-x#6587]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using the `ampm={false}` prop and passing a `Date` object instead of null, the timepicker doesn't allow erasing the minutes by pressing backspace, unless you select both digits and then.

[bug-timepicker.webm](https://user-images.githubusercontent.com/30949004/197204919-028a736e-93ff-4c97-b251-9956a2b3fb2d.webm)

Selecting both digits and then erasing works, but as soon as you type one digit, it fills in two digits, like shown in the video.

This doesn't work if the first value to be passed is `null`.

### Expected behavior 🤔

The user should be able to erase the time with the backspace key, digit by digit.

### Steps to reproduce 🕹

Link to live example: [demo](https://codesandbox.io/s/sleepy-brook-j3olef?file=/demo.tsx)

Steps:
1. Try to use backspace to erase the time in the provided text field.
2. Notice it doesn't allow you to.
3. Replace `React.useState<Date | null>(new Date());` with `React.useState<Date | null>(null);`
4. Notice you can freely type in a time and erase it, without bugs.

### Context 🔦

I'm trying to make a timepicker that receives a default value of `00:00` or a value provided by the server.

**Comment by alexfauquette** [comment]
The problem comes from the date-io adapter or the library. If you do the same with `dayjs` you don't have the problem.
https://codesandbox.io/s/nifty-thunder-ye967g?file=/demo.tsx

To be more specific, Th problem is the milliseconds that are not set to 0 in date-fns

**Comment by alexfauquette** [comment]
Fixed by #6618

**Comment by nollidnosnhoj** [comment]
Hello, I think this bug still persists in the latest version.

https://codesandbox.io/s/romantic-alex-od8xr0?file=/demo.tsx

It works when I set the initial value to now (new Date()), but any other date does not work.

**Comment by alexfauquette** [comment]
Because it will be available in next release

At the end of PR, GitHub display which tag (release version for us) is the first one to have the PR included. Seems this one is not included in any release

![image](https://user-images.githubusercontent.com/45398769/199676442-f81efdca-e109-44e7-989d-2e81b8fa9d4c.png)

**Comment by alexfauquette** [comment]
@nollidnosnhoj It's not exactly the same bug.

The original issue was buggy because date-fns takes into account the milliseconds when doing the time equality check.

Here it's because when parsing the input, the default date is set to today. The bug disapear if you set the initial value to today and set the hours/minutes as follow:

```js
const initialDate = new Date();

initialDate.setHours(10)
initialDate.setMinutes(0)
```

**Comment by nollidnosnhoj** [comment]
@alexfauquette I see. That makes sense. It works now. Thanks!

**Comment by flaviendelangle** [comment]
I am closing this issue.

We recently launched the first beta of `@mui/x-date-pickers` and `@mui/x-date-pickers-pro` v6.x.
This new version contains a full rework of the input editing.
You can have a look at [the v6 doc](https://next.mui.com/x/react-date-pickers/time-picker/) which is currently in beta and the [related blog post](https://mui.com/blog/v6-beta-pickers/).

We won't apply complicated (and not always doable) fixes to the v5 version, I hope this new version solves your problem.
