### ISSUE TITLE
Live demo locks up the browser

### ISSUE THREAD

**Issue by Janpot** [mui/mui-x#7669]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:

1. Open https://mui.com/x/react-data-grid/#commercial-version
2. Open the code of the pro demo by clicking `<>`
3. Delete the line `rowHeight={38}`
4. type `getRowHeight={() => 'auto'}`. type it, pasting doesn't trigger this. (in case it matters, the exact sequence I type is `g` `e` `t` `R` `o` `w` `H` `e` `i` `g` `h` `t` `=` `{` `}` `Arrow left` `(` `)` ` ` `=` `>` ` ` `'` `'` `Arrow left` `a` `u` `t` `o` )

### Current behavior 😯

The page locks up, usually at the point where I get to `getRowHeight={() => 'a'}`. I can't do anything but close the browser tab.

### Expected behavior 🤔

The page doesn't lock up, and renders the table with auto row height.

### Context 🔦

Was trying something out in the demos when this happened, then noticed I could repeatedly reproduce this behavior.

Not sure whether this is an issue with the live demos or the datagrid. Tagging @mui/xgrid as well.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Thanks, @Janpot 
I can reproduce it on deployment from the `next` branch as well: https://next.mui.com/x/react-data-grid/#commercial-version
Additionally, there's a selection issue on the `next` version:
<img width="494" alt="Screenshot 2023-01-23 at 11 44 29" src="https://user-images.githubusercontent.com/13808724/214020671-368f722f-0594-4c58-9eea-1989b4ad659b.png">

We should upgrade the monorepo first and then investigate what causes the issue if it's still present after the upgrade

**Comment by LukasTy** [comment]
@cherniavskii your mentioned code selection issue seems to be resolved with a [`next` package bump](https://github.com/mui/mui-x/pull/7659). 😉

**Comment by cherniavskii** [comment]
@LukasTy Great!

**Comment by cherniavskii** [comment]
I cannot reproduce the issue with the datagrid itself: https://codesandbox.io/s/focused-ellis-lw5u62?file=/demo.tsx
So it's probably related to live editing

**Comment by LukasTy** [comment]
> I cannot reproduce the issue with the datagrid itself: https://codesandbox.io/s/focused-ellis-lw5u62?file=/demo.tsx So it's probably related to live editing

Maybe that feature can be turned off for certain demos?
I tried live editing with it and IMHO it's just not suited for such an example, because it is lagging like crazy on even a high-end MacBook. 🤔

**Comment by Janpot** [comment]
Yes, my hunch was that this was mostly related to live editing. That's why I originally opened this ticket on the core repo.

If I had to make a guess I'd say that it's something in `react-runner`. (tagging @nihgwu, you may be interested in this specific case).

Are we debouncing the code input before feeding it to `react-runner`?

**Comment by nihgwu** [comment]
I think it's a problem of the DataGrid itself, without the `getRowHeight` change it works well

**Comment by cherniavskii** [comment]
Thanks, everyone for your input!
I've submitted a PR with the fix 🚀

**Comment by oliviertassinari** [comment]
> there's a selection issue on the next version:
> 
> <img width="494" alt="Screenshot 2023-01-23 at 11 44 29" src="https://user-images.githubusercontent.com/13808724/214020671-368f722f-0594-4c58-9eea-1989b4ad659b.png">

@cherniavskii I looked at it two weeks ago. It's an issue with this line: https://github.com/mui/material-ui/blob/64e83d53d7afca1d92a9b1c4c0cc05dc0081338c/docs/src/modules/components/ThemeContext.js#L171

This means that we load this file https://next.mui.com/static/styles/prism-okaidia.css, which resolves to https://master--material-ui-x.netlify.app/static/styles/prism-okaidia.css (wrong) and not https://next--material-ui-x.netlify.app/static/styles/prism-okaidia.css (correct). It will be fixed once we make MUI X v6 stable.

**Comment by cherniavskii** [comment]
@oliviertassinari looks like the selection issue is solved already - see https://github.com/mui/mui-x/issues/7669#issuecomment-1402078935

**Comment by LukasTy** [comment]
> looks like the selection issue is solved already - see [#7669 (comment)](https://github.com/mui/mui-x/issues/7669#issuecomment-1402078935)

It looks like it is still an issue, at least with deployed docs, as Olivier mentioned.
In PR previews it's not reproducible, so, probably not worth spending the time trying to fix it, when it will not longer be a problem with v6 stable release. 🙈
